### ISSUE TITLE
Python 3.8 FileNotFoundError: [WinError 2] 

### ISSUE THREAD

**Issue by netsap** [leonsmith/pydig#13]
I am able to run my code on both my Linux and MacOS Machines, on Windows I get a FileNotFoundError.

Python 3.8 was installed via the [Microsoft Store](https://www.microsoft.com/en-us/p/python-38/9mssztt1n39l). 
Visual Studio Code is being used to run the code, I have also tried it through powershell.

It fails when it attempts to run `ip_str = dns_query(site_url, 'A')` dns_query refers to a pydig import `from pydig import query as dns_query`

pydig was installed through a pip3 requirements file.

Traceback:

```
 Traceback (most recent call last):
      File "c:/Users/Overflow/Documents/Uni/Project/ShodanQueryTool/prototypes/yelp_scraper.py", line 57, in <module>
        page_scraper()
      File "c:/Users/Overflow/Documents/Uni/Project/ShodanQueryTool/prototypes/yelp_scraper.py", line 21, in page_scraper
        format_unformatted_urls(unformatted_urls)
      File "c:/Users/Overflow/Documents/Uni/Project/ShodanQueryTool/prototypes/yelp_scraper.py", line 30, in format_unformatted_urls
        site_scraper(yelp_url)
      File "c:/Users/Overflow/Documents/Uni/Project/ShodanQueryTool/prototypes/yelp_scraper.py", line 49, in site_scraper
        ip_str = dns_query(site_url, 'A')
      File "C:\Users\Overflow\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pydig\resolver.py", line 78, in query
        output = self._execute(args).decode(self.encoding).strip()
      File "C:\Users\Overflow\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pydig\resolver.py", line 42, in _execute
        return subprocess.check_output(args)  # pragma: no cover
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 411, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 489, in run
        with Popen(*popenargs, **kwargs) as process:
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 854, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1307, in _execute_child
        hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
    FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by MiDoSaMi** [comment]
You need to install dig tools (from binds) on windows.
follow this: https://help.dyn.com/how-to-use-binds-dig-tool/
