### ISSUE TITLE
Clarify Python 3.4 Compability

### ISSUE THREAD

**Issue by leonsmith** [leonsmith/pydig#3]
Python 3.4's is not receiving any more support, think the pyproject.toml file have the wrong minimum dep number

**Comment by Phoenix1112** [comment]
@leonsmith Is this the reason why the pydig program does not work with python3.8 in windows? The pydig module works in linux with python3.7. please can you tell me if there is a solution to the problem below?


```
>>> import pydig
>>> a = pydig.query("starbucks.com","A")

Traceback (most recent call last):
  File "<pyshell#37>", line 1, in <module>
    a = pydig.query("starbucks.com","A")
  File "C:\Users\levent\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pydig\resolver.py", line 78, in query
    output = self._execute(args).decode(self.encoding).strip()
  File "C:\Users\levent\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pydig\resolver.py", line 42, in _execute
    return subprocess.check_output(args)  # pragma: no cover
  File "C:\Users\levent\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\levent\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\levent\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\levent\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

```

**Comment by leonsmith** [comment]
0.3.0 is now marked as compatible with python 3.8 👍

**Comment by Phoenix1112** [comment]
@leonsmith first of all thank you for writing an answer. but the same problem persists. After deleting the old pyding version, I installed the new version. but i see the same errors above. ???
python version : 3.8.2

**Comment by leonsmith** [comment]
Ohh appoligies, @Phoenix1112 I assumed this was a python 3.8 issue but it's looks like it's a window specific issue.

I don't belive windows comes with `dig` pre-installed so might be worth running through the following link to https://www.digitalocean.com/docs/networking/dns/resources/use-dig/ install it but I don't have a windows computer to install and test it under I'm afraid
